### Wyślij task
POST http://localhost:8081/tasks
Accept: application/json
Content-Type: application/json

{
  "id": "111",
  "name": "test 111",
  "description": "Opis zadania ...",
  "workspaceUrl": "/Users/rafalnowak/PycharmProjects/task1",
  "status": "SUBMITTED"
}
